### ISSUE TITLE
in which dir to build rocketchip?

### ISSUE THREAD

**Issue by meton-robean** [rhit-neuro/deca#1]
hi, in which dir to run the following commands?
    make rocket CONFIG=ZynqFPGAMyAcceleratorConfig ROCKETCHIP_ADDONS=accelerators
    make project CONFIG=ZynqFPGAMyAcceleratorConfig ROCKETCHIP_ADDONS=accelerators
    make CONFIG=ZynqFPGAMyAcceleratorConfig ROCKETCHIP_ADDONS=accelerators

**Comment by heidecjj** [comment]
`fpga-zynq/zedboard`, `fpga-zynq/zybo`, or `fpga-zynq/zc706` depending on which development board you're using
